import { useEffect } from 'react';
import { BasketItemKind } from '../State/BasketState';
import { useBasketContext, useBasketDispatchContext } from '../State/Basketcontext';
import { useProductContext } from '../State/Productcontext';
import { storeBasketInSession } from '../State/SessionStorage';


/* Partly generated by AI, all state is not generated with AI*/
function LandingPage() {
  const basketDispatcher = useBasketDispatchContext();
  const products = useProductContext();
  const basket = useBasketContext();

  useEffect(()=>{
    function handeReloadPage(){
      console.log("Logging to session storage");
      storeBasketInSession(basket);
    }
    window.addEventListener("beforeunload",handeReloadPage);

    return ()=>{
      window.removeEventListener("beforeunload",handeReloadPage);
    };

  },[basket]);


  return (
    <div className="landing-page-container">
      <h1>This is a landing page</h1>
      <p>The very first page the customer sees, and where they'll be able to pick the items they want to buy</p>
      <div className="products-container">
        {products.map((product) => (
          <div className="product-card" key={product.product_id} aria-label="product">
            <h2 className="product-name">{product.name}</h2>
            <p className="product-description" title="price">{product.price} {product.currency}</p>
            <div className='addButton'>
              <button className="add-to-cart-button" onClick={() => basketDispatcher({type: BasketItemKind.ADDTOBASKET,productinfo:product})}>Add to cart</button>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}


export default LandingPage;