import { BasketItemKind } from '../State/BasketState';
import { useBasketDispatchContext } from '../State/Basketcontext';
import { useProductContext } from '../State/Productcontext';


/* Partly generated by AI, all state is not generated with AI*/
function LandingPage() {
  const basketDispatcher = useBasketDispatchContext();
  const products = useProductContext();


  return (
    <div className="landing-page-container">
      <h1>This is a landing page</h1>
      <p>The very first page the customer sees, and where they'll be able to pick the items they want to buy</p>
      <div className="products-container">
        {products.map((product) => (
          <div className="product-card" key={product.product_id}>
            <h2 className="product-name">{product.name}</h2>
            <p className="product-description">{product.price} {product.currency}</p>
            <button className="add-to-cart-button" onClick={() => basketDispatcher({type: BasketItemKind.ADDTOBASKET,productinfo:product})}>Add to cart</button>
          </div>
        ))}
      </div>
    </div>
  )
}


export default LandingPage;