import { BasketItemKind } from '../State/BasketState';
import { useBasketDispatchContext } from '../State/Basketcontext';
import { ProductInfo } from '../TSReusedTypes/ItemsAndPrices';

interface landingPageProps {
    products: ProductInfo[]
  }

/* Partly generated by AI */
function LandingPage({products }: landingPageProps) {
    const basketDispatcher = useBasketDispatchContext();


    return (
        <div className="landing-page-container">
            <h1>This is a landing page</h1>
            <p>The very first page the customer sees, and where they'll be able to pick the items they want to buy</p>
            <div className="products-container">
                {products.map((product) => (
                    <div className="product-card" key={product.id}>
                        <h2 className="product-name">{product.name}</h2>
                        <p className="product-description">{product.price} {product.currency}</p>
                        <button className="add-to-cart-button" onClick={() => basketDispatcher({type: BasketItemKind.ADDTOBASKET,productinfo:product})}>Add to cart</button>
                    </div>
                ))}
            </div>
        </div>
    )
}


export default LandingPage;